config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'

  resources :movies do
    post 'set_rating', on: :member
    post 'filter', on: :collection
  end

  resources :categories
  resources :ratings
  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :bigint           not null, primary key
#  text        :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#
# Indexes
#
#  index_movies_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Movie < ActiveRecord::Base
    belongs_to :category
    has_many :ratings, dependent: :destroy

    def average_rating
        ratings.average(:rating)
    end

end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :bigint           not null, primary key
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  movie_id   :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_ratings_on_movie_id              (movie_id)
#  index_ratings_on_user_id               (user_id)
#  index_ratings_on_user_id_and_movie_id  (user_id,movie_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (movie_id => movies.id)
#  fk_rails_...  (user_id => users.id)
#
class Rating < ApplicationRecord
    belongs_to :user
    belongs_to :movie
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all.page(params[:page])
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
    
        if @category.save
          redirect_to @category
        else
          render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        
        if @category.update(category_params)
            redirect_to @category
        else
            render :edit
        end
    end 

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
    
        redirect_to categories_path
    end
      
    private
    
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        fill_dictionaries
        if params[:category_id]
            @movies = Movie.where(category_id: params[:category_id]).page(params[:page])
        else
            @movies = Movie.all.page(params[:page])
        end
    end

    def show
        @movie = Movie.find(params[:id])
        @rating = Rating.where(user: current_user, movie: @movie).first
    end

    def new
        @movie = Movie.new
        fill_dictionaries
    end

    def create
        @movie = Movie.new(movie_params)
    
        if @movie.save
          redirect_to @movie
        else
          render :new
        end
    end

    def edit
        @movie = Movie.find(params[:id])
        fill_dictionaries
    end
    
    def update
        @movie = Movie.find(params[:id])
        
        if @movie.update(movie_params)
            redirect_to @movie
        else
            render :edit
        end
    end 

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
    
        redirect_to movies_path
    end

    def set_rating
       Rating.create(user_id: current_user.id, movie_id: params[:id], rating: movie_params[:rating])
       redirect_to movie_path
    end

    def filter
        if params[:category].empty?
            redirect_to movies_path
        else
            redirect_to movies_path(category_id: params[:category])
        end
    end

    private
    
    def movie_params
      params.require(:movie).permit(:category_id, :title, :rating, :text)
    end

    def fill_dictionaries
        @categories = Category.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field(:name, {:class => 'form-control'}) %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<br/>
  
  <div>
    <%= form.submit({:class => 'btn btn-success'}) %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit category Info</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<%= button_to "New Category", new_category_path, method: :get, class: 'btn btn-outline-success' %>
<table>
    <tr>
        <td> Category </td>
    <% @categories.each do |category| %>
        <tr>
            <td> <%= category.name %> </td>
            <td> <%= button_to "Show", category_path(category), method: :get, class: 'btn btn-primary' %> </td>
            <td> <%= button_to "Edit", edit_category_path(category), method: :get, class: 'btn btn-info' %> </td>
            <td> <%= button_to "Destroy", category_path(category), 
                    class: 'btn btn-danger',
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td>
        </tr>
    <% end %>
    <br/>
</table>
<%= paginate @categories, theme: 'bootstrap-5' %>

app/views/categories/new.html.erb
<h1>Edit category Info</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h2>Category info</h2>

№: <%= @category.id %><br/>
Name: <%= @category.name %><br/>

<%= link_to "Back to list", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <nav class="d-inline-flex mt-2 mt-md-0" style="margin-left: 15px;" >
        <a class="me-3 py-2 text-dark text-decoration-none" href="/movies">Movies</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="/categories">Categories</a>
      </nav>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <% if user_signed_in? %>
        <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn me-3 py-2 text-dark text-decoration-none" %>
      <% else %>
        <a class="py-2 text-dark text-decoration-none" href="/users/sign_in">Sign in</a>
      <%end%>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/movies/_average_rating.html.erb
Average rating: <%= movie.average_rating %>

app/views/movies/_filter.html.erb
<%= form_with model: movie, url: filter_movies_path  do |form| %>
  <div>
    <%= form.label :category_name %>
    <%= form.collection_select :category, categories, :id, :name, {selected: params[:category_id],
    include_blank: "All Categories"  } %> 
    <%= form.submit("Filter", {class: 'btn btn-success'}) %>
  </div>
<% end %>

app/views/movies/_form.html.erb
<%= form_with model: movie do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field(:title, {class: 'form-control'}) %>
    <% movie.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :category_name %>
    <%= form.collection_select :category_id, categories, :id, :name %> 
  </div>
  
  <div>
    <%= form.label :text %>
    <%= form.text_field(:text, {class: 'form-control'}) %>
    <% movie.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<br/>
  
  <div>
    <%= form.submit({class: 'btn btn-success'}) %>
  </div>

<% end %>

app/views/movies/_rating.html.erb
<%= form_with model: movie, url: set_rating_movie_path, method: :post do |form|%>
  <div>
    <%= form.label :rating %>
    <%= form.select(:rating, options_for_select(1..10), include_blank: "Do not ready to answer") %>
  </div>
   
  <div>
    <%= form.submit({method: :post, class: 'btn btn-success'})%>
  </div>
<% end %>

app/views/movies/_rating_by_user.html.erb
Your rating for this movie is: <%= rating.rating %>

app/views/movies/edit.html.erb
<h1> Edit Movie </h1>

<%= render "form", movie: @movie, categories: @categories %>

app/views/movies/index.html.erb
<h3>Movies</h3> 
<%= render "filter", movie: @movie, categories: @categories %>
<%= button_to "New movie", new_movie_path, method: :get, class: 'btn btn-outline-success' %>

<table>

    <tr>
        <th> Movie </th>
        <th> Category </th>
        <th> About </th>
    </tr>
    <% @movies.each do |movie| %>
        <tr>
            <td> <%= movie.title %> </td>
            <td> <%= movie.category.name %> </td>
            <td> <%= movie.text %> </td>
            <td> <%= button_to "Show", movie_path(movie), method: :get, class: 'btn btn-primary' %> </td>
            <td> <%= button_to "Edit", edit_movie_path(movie), method: :get, class: 'btn btn-info' %> </td>
            <td> <%= button_to "Destroy", movie_path(movie), 
                    class: 'btn btn-danger',
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td>
        </tr>  
    <% end %>
</table>
<%= paginate @movies, theme: 'bootstrap-5' %> 

app/views/movies/new.html.erb
<h1> New Movie </h1>

<%= render "form", movie: @movie, categories: @categories %>

app/views/movies/show.html.erb
<h2>Movie info</h2>

Name: <%= @movie.title %><br/>
About: <%= @movie.text %><br/>

<br/>
<% if user_signed_in?%>
    <% if @rating.nil? %>
        <%= render "rating", movie: @movie %>
    <% else %>
        <%= render "rating_by_user", rating: @rating %>
    <% end %>
<% end %>
<br/>
<br/>
<%= render "average_rating", movie: @movie %>
<br/>
<br/>
<%= link_to "Back to list", movies_path %>